### CRIAR
POST http://127.0.0.1:5000/tasks
Content-Type: application/json

{
    "title": "Testar o CRUD completo",
    "description": "Se essa tarefa for criada, o POST funciona."
}

### LISTAR TUDO
GET http://127.0.0.1:5000/tasks

### LER APENAS UMA
GET http://127.0.0.1:5000/tasks/1

### ATUALIZAR
PUT http://127.0.0.1:5000/tasks/1
Content-Type: application/json

{
    "title": "Testar o CRUD completo (Concluído)",
    "description": "Atualizei o status para feito!",
    "done": true
}

### VERIFICAR ATUALIZAÇÃO
GET http://127.0.0.1:5000/tasks/1

### DELETAR
DELETE http://127.0.0.1:5000/tasks/1

### TESTA SE A TAREFA FOI DELETADA
GET http://127.0.0.1:5000/tasks/1